{"identifier":{"url":"doc:\/\/Discord\/documentation\/Discord\/DiscordGatewayCloseReason\/invalidSequence","interfaceLanguage":"swift"},"metadata":{"title":"invalidSequence","symbolKind":"property","modules":[{"name":"Discord"}],"role":"symbol","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidSequence"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7Discord0A18GatewayCloseReasonV","kind":"typeIdentifier","text":"DiscordGatewayCloseReason"}],"externalID":"s:7Discord0A18GatewayCloseReasonV15invalidSequenceACvpZ"},"hierarchy":{"paths":[["doc:\/\/Discord\/documentation\/Discord","doc:\/\/Discord\/documentation\/Discord\/DiscordGatewayCloseReason"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/discord\/discordgatewayclosereason\/invalidsequence"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"We sent a bad sequence number when trying to resume.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["Linux"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidSequence","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7Discord0A18GatewayCloseReasonV","identifier":"doc:\/\/Discord\/documentation\/Discord\/DiscordGatewayCloseReason","text":"DiscordGatewayCloseReason","kind":"typeIdentifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":2},"references":{"doc://Discord/documentation/Discord/DiscordGatewayCloseReason/invalidSequence":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidSequence"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7Discord0A18GatewayCloseReasonV","text":"DiscordGatewayCloseReason","kind":"typeIdentifier"}],"abstract":[{"text":"We sent a bad sequence number when trying to resume.","type":"text"}],"type":"topic","identifier":"doc:\/\/Discord\/documentation\/Discord\/DiscordGatewayCloseReason\/invalidSequence","title":"invalidSequence","role":"symbol","url":"\/documentation\/discord\/discordgatewayclosereason\/invalidsequence"},"doc://Discord/documentation/Discord":{"url":"\/documentation\/discord","identifier":"doc:\/\/Discord\/documentation\/Discord","type":"topic","kind":"symbol","role":"collection","abstract":[],"title":"Discord"},"doc://Discord/documentation/Discord/DiscordGatewayCloseReason":{"url":"\/documentation\/discord\/discordgatewayclosereason","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DiscordGatewayCloseReason","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"DiscordGatewayCloseReason","kind":"identifier"}],"identifier":"doc:\/\/Discord\/documentation\/Discord\/DiscordGatewayCloseReason","title":"DiscordGatewayCloseReason","kind":"symbol","abstract":[{"text":"Represents the reason a gateway was closed.","type":"text"}]}}}